hostname = ""
bind-address = ""
port = 8086
reporting-disabled = false

[initialization]
  join-urls = ""

[authentication]
  enabled = false

[admin]
  enabled = true
  port = 8083

[api]
  bind-address = ""
  port = 0
  ssl-port = 0
  ssl-cert = ""
  read-timeout = "0"

[collectd]
  bind-address = ""
  port = 0
  database = ""
  enabled = false
  typesdb = ""

[opentsdb]
  address = ""
  port = 0
  enabled = false
  database = ""
  retention-policy = ""

[udp]
  enabled = false
  bind-address = ""
  port = 0

[broker]
  dir = "/data/broker"
  enabled = true
  election-timeout = "0"
  truncation-interval = "10m0s"
  max-topic-size = 1073741824
  max-segment-size = 10485760

[data]
  dir = "/data/db"
  enabled = true
  retention-auto-create = true
  retention-check-enabled = true
  retention-check-period = "10m0s"
  retention-create-period = "45m0s"

[snapshot]
  enabled = true

[logging]
  http-access = true
  write-tracing = false
  raft-tracing = false

[monitoring]
  enabled = false
  write-interval = "1m0s"

[debugging]
  pprof-enabled = false

[continuous_queries]
  recompute-previous-n = 2
  recompute-no-older-than = "10m0s"
  compute-runs-per-interval = 10
  compute-no-more-than = "2m0s"
  disabled = false